import Foundation

/// ADAPTER: the `~/.lldbinit-Xcode` stop-hook -> `XcodeHookInstalling`. Writes a generated source file
/// under Application Support and a bracketed block into the Xcode init. Paths are injectable for tests.
public struct LldbHookInstaller: XcodeHookInstalling {
    private let xcodeInitURL: URL
    private let fauxInitURL: URL

    public init(
        xcodeInitURL: URL = FileManager.default.homeDirectoryForCurrentUser.appendingPathComponent(".lldbinit-Xcode"),
        fauxInitURL: URL = LldbHookInstaller.defaultFauxInitURL()
    ) {
        self.xcodeInitURL = xcodeInitURL
        self.fauxInitURL = fauxInitURL
    }

    public func install(dylibPath: String) async throws {
        try writeFauxInit(dylibPath: dylibPath)
        let content = (try? String(contentsOf: xcodeInitURL, encoding: .utf8)) ?? ""
        let updated = LldbInitBlock.inserting(sourcePath: fauxInitURL.path, into: content)
        try updated.write(to: xcodeInitURL, atomically: true, encoding: .utf8)
    }

    public func uninstall() async {
        if let content = try? String(contentsOf: xcodeInitURL, encoding: .utf8) {
            try? LldbInitBlock.removing(from: content).write(to: xcodeInitURL, atomically: true, encoding: .utf8)
        }
        try? FileManager.default.removeItem(at: fauxInitURL)
    }

    public func isInstalled() async -> Bool {
        (try? String(contentsOf: xcodeInitURL, encoding: .utf8))?.contains(LldbInitBlock.begin) ?? false
    }

    private func writeFauxInit(dylibPath: String) throws {
        try FileManager.default.createDirectory(at: fauxInitURL.deletingLastPathComponent(), withIntermediateDirectories: true)
        let body = """
        # Generated by FauxCam — auto-removed when auto-mode is off or FauxCam quits.
        target stop-hook add -n main -o 'process load "\(dylibPath)"'
        """
        try body.write(to: fauxInitURL, atomically: true, encoding: .utf8)
    }

    public static func defaultFauxInitURL() -> URL {
        let support = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
        return support.appendingPathComponent("com.fauxcam/faux-lldbinit")
    }
}
