import Foundation

/// ADAPTER: the `~/.lldbinit-Xcode` stop-hook -> `XcodeHookInstalling`. Writes a generated source file
/// under Application Support and a bracketed block into the Xcode init. Paths are injectable for tests.
public struct LldbHookInstaller: XcodeHookInstalling {
    public enum InstallError: Error, Equatable { case dylibMissing(path: String) }

    private static let hookBreakpointName = "FauxCam_hook"
    private static let generatedFileHeader = "# Generated by FauxCam — auto-removed when auto-mode is turned off or FauxCam quits."

    private let xcodeInitURL: URL
    private let fauxInitURL: URL

    public init(
        xcodeInitURL: URL = FileManager.default.homeDirectoryForCurrentUser.appendingPathComponent(".lldbinit-Xcode"),
        fauxInitURL: URL = LldbHookInstaller.defaultFauxInitURL()
    ) {
        self.xcodeInitURL = xcodeInitURL
        self.fauxInitURL = fauxInitURL
    }

    public func install(dylibPath: String) async throws {
        guard !dylibPath.isEmpty, FileManager.default.fileExists(atPath: dylibPath) else {
            throw InstallError.dylibMissing(path: dylibPath)
        }
        try writeFauxInit(dylibPath: dylibPath)
        // Only an ABSENT file is treated as empty: a read failure on an existing file must propagate, never
        // be swallowed into "" — that would overwrite the user's ~/.lldbinit-Xcode with only our block.
        let existingContent = FileManager.default.fileExists(atPath: xcodeInitURL.path)
            ? try String(contentsOf: xcodeInitURL, encoding: .utf8)
            : ""
        let updated = LldbInitBlock.inserting(sourcePath: fauxInitURL.path, into: existingContent)
        try updated.write(to: xcodeInitURL, atomically: true, encoding: .utf8)
    }

    public func uninstall() async {
        if let content = try? String(contentsOf: xcodeInitURL, encoding: .utf8) {
            let cleaned = LldbInitBlock.removing(from: content)
            if cleaned.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
                try? FileManager.default.removeItem(at: xcodeInitURL)   // FauxCam created the file: take it with us
            } else if cleaned != content {
                try? cleaned.write(to: xcodeInitURL, atomically: true, encoding: .utf8)
            }
        }
        try? FileManager.default.removeItem(at: fauxInitURL)
    }

    public func isInstalled() async -> Bool {
        (try? String(contentsOf: xcodeInitURL, encoding: .utf8))?.contains(LldbInitBlock.begin) ?? false
    }

    private func writeFauxInit(dylibPath: String) throws {
        try FileManager.default.createDirectory(at: fauxInitURL.deletingLastPathComponent(), withIntermediateDirectories: true)
        let body = """
        \(Self.generatedFileHeader)
        breakpoint set -n main -N \(Self.hookBreakpointName) -o true
        target stop-hook add -n main -o 'process load "\(dylibPath)"' -G true

        """
        try body.write(to: fauxInitURL, atomically: true, encoding: .utf8)
    }

    public static func defaultFauxInitURL() -> URL {
        let support = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
        return support.appendingPathComponent("com.fauxcam/faux-lldbinit")
    }
}
