import Foundation

/// Installs (and cleanly removes) the LLDB stop-hook that auto-injects the guest dylib into every
/// simulator-launched app. Unlike tools that leave this behind forever, install/uninstall is
/// reversible and bracketed: it only ever adds/removes its own marked block in `~/.lldbinit-Xcode`,
/// preserving anything else there, and the app removes it on quit.
public struct LldbInjectionInstaller {
    public enum InstallError: Error { case dylibMissing(String) }

    static let beginMarker = "# >>> FauxCam auto-inject (remove with FauxCam) >>>"
    static let endMarker = "# <<< FauxCam auto-inject <<<"

    private let dylibPath: String
    private let xcodeLldbinitURL: URL
    private let fauxLldbinitURL: URL
    private let fileManager: FileManager

    public init(dylibPath: String,
                xcodeLldbinitURL: URL = FileManager.default.homeDirectoryForCurrentUser.appendingPathComponent(".lldbinit-Xcode"),
                fauxLldbinitURL: URL = LldbInjectionInstaller.defaultFauxLldbinitURL(),
                fileManager: FileManager = .default) {
        self.dylibPath = dylibPath
        self.xcodeLldbinitURL = xcodeLldbinitURL
        self.fauxLldbinitURL = fauxLldbinitURL
        self.fileManager = fileManager
    }

    public static func defaultFauxLldbinitURL() -> URL {
        let support = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first
            ?? FileManager.default.homeDirectoryForCurrentUser.appendingPathComponent("Library/Application Support")
        return support.appendingPathComponent("com.fauxcam/faux-lldbinit")
    }

    public var isInstalled: Bool {
        guard let content = try? String(contentsOf: xcodeLldbinitURL, encoding: .utf8) else { return false }
        return content.contains(Self.beginMarker)
    }

    public func install() throws {
        guard fileManager.fileExists(atPath: dylibPath) else { throw InstallError.dylibMissing(dylibPath) }
        try writeFauxLldbinit()

        let existing = (try? String(contentsOf: xcodeLldbinitURL, encoding: .utf8)) ?? ""
        guard !existing.contains(Self.beginMarker) else { return }   // idempotent
        let block = "\(Self.beginMarker)\ncommand source \"\(fauxLldbinitURL.path)\"\n\(Self.endMarker)\n"
        let separator = (existing.isEmpty || existing.hasSuffix("\n")) ? "" : "\n"
        try (existing + separator + block).write(to: xcodeLldbinitURL, atomically: true, encoding: .utf8)
    }

    public func uninstall() {
        if let content = try? String(contentsOf: xcodeLldbinitURL, encoding: .utf8) {
            let cleaned = Self.removingBlock(from: content)
            if cleaned.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
                try? fileManager.removeItem(at: xcodeLldbinitURL)
            } else if cleaned != content {
                try? cleaned.write(to: xcodeLldbinitURL, atomically: true, encoding: .utf8)
            }
        }
        try? fileManager.removeItem(at: fauxLldbinitURL)
    }

    private func writeFauxLldbinit() throws {
        try fileManager.createDirectory(at: fauxLldbinitURL.deletingLastPathComponent(), withIntermediateDirectories: true)
        let body = """
        # Generated by FauxCam — auto-removed when auto-mode is turned off or FauxCam quits.
        breakpoint set -n main -N FauxCam_hook -o true
        target stop-hook add -n main -o 'process load "\(dylibPath)"' -G true

        """
        try body.write(to: fauxLldbinitURL, atomically: true, encoding: .utf8)
    }

    /// Removes the marked block (inclusive) and nothing else.
    static func removingBlock(from content: String) -> String {
        guard content.contains(beginMarker) else { return content }
        var kept: [Substring] = []
        var insideBlock = false
        for line in content.split(separator: "\n", omittingEmptySubsequences: false) {
            if line.contains(beginMarker) { insideBlock = true; continue }
            if insideBlock {
                if line.contains(endMarker) { insideBlock = false }
                continue
            }
            kept.append(line)
        }
        return kept.joined(separator: "\n")
    }
}
